version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install -e "./ragas[docs]"
    - if [ -n "$GH_TOKEN" ]; then pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git; fi
    - mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
