# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.0.1a2.dev23+g10ed261.d20230513"
__version_tuple__ = version_tuple = (0, 0, 1, "dev23", "g10ed261.d20230513")
