name: Upload ragas-examples Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi-release
    strategy:
      matrix:
        package:
          - name: ragas-examples
            directory: examples
            token: PYPI_API_TOKEN
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools setuptools_scm[toml] build 
    - name: get setuptools-scm version 
      run: python -m setuptools_scm
      working-directory: ${{ matrix.package.directory }}
    - name: Build package
      run: python -m build
      working-directory: ${{ matrix.package.directory }}
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets[matrix.package.token] }}
        packages-dir: ${{ matrix.package.directory }}/dist/
        attestations: false


